# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Maine-eDNA
email: laura.jackson@maine.edu
author: Maine-eDNA
url: "https://laurajackson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "laurajackson/bioinformatics_workshop_2021"
github_username:  Maine-eDNA

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

highlighter: rouge

whitelist:
  - jekyll-redirect-from

# Exclude from processing.  # 
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
